### PR TITLE
Add zstd compression support for session loading/saving.

### PR DESCRIPTION
**Pull request by KerfuffleV2**
I moved the actual file reading/writing stuff into the CLI, seems to me IO type stuff doesn't really belong in a library. This would also make it possible for people to use different compression if they wanted in the future.

Just trying to stream the data through a zstd wrapper didn't work (it was insanely slow). I changed the serialization to skip the actual memory field data, that is read+decompressed/written+compressed after the header. I added the memory k/v lengths to that struct as well.

There also was a bug in the `inference_with_prompt` function where it wouldn't honor the requested token count so your suggestion about using `-n 0` to just save the prompt didn't work — it would always generate a few more tokens.

### CODE REVIEW

**Comment by philpax** [comment]
Nice! I'm actually just updating the PR to the latest version of llama-rs, so I'll fix up my PR and merge this into it.

**Comment by KerfuffleV2** [comment]
Sounds good. Anything you'd want me to change first?

**Comment by philpax** [comment]
Nah, seems pretty reasonable. Could you try bringing the data back into the snapshot and using https://crates.io/crates/serde_bytes and seeing if that helps with the writer problem? My suspicion is that it's trying to call the write function for every single byte, which is why it's slow.

**Comment by KerfuffleV2** [comment]
I'm working on the first part at least. I hate merging so much.

**Comment by philpax** [comment]
Even if it's a `BufWriter`, I assume that the dispatch would be pretty costly. It's worth a try, at least!

**Comment by KerfuffleV2** [comment]
@philpax Welp, seems like I was completely wrong. I'm really surprised, actually.

Anyway, there's certainly no argument for using the much more complicated approach. Thanks for the tip!

**Comment by philpax** [comment]
No worries, it's the kind of thing you only learn after having bit by it once or twice 😅

**Review by philpax — APPROVED** [review]

**Pull request merged**
